### ISSUE TITLE
Parsing Chart.yaml ?

### ISSUE THREAD

**Issue by sparqueur** [kubepack/chart-doc-gen#14]
Hi,

Your project is really geat :+1: 
However, why do we have to provide a `doc.yaml` which contains a `chart` block ?
The Chart.yaml could be used as an input, no ?

**Comment by chgl** [comment]
Some fields in doc.yaml don't have a correspondence in Chart.yaml, e.g. doc.yaml's `repository.url/name.` But I think the Chart.yaml's annotations could be used for this, something like:

```yaml
apiVersion: v2
name: test
description: A Helm chart for deploying the test app on Kubernetes.
type: application
version: 1.0.0
annotations:
  chart-doc-gen.appscode.com/repository-url: https://charts.appscode.com/stable/
  chart-doc-gen.appscode.com/repository-name: appscode
  # ...
```

With some reasonable defaults if the annotations aren't used?
