### ISSUE TITLE
[Feature Request] Parent object documenation

### ISSUE THREAD

**Issue by sparqueur** [kubepack/chart-doc-gen#15]
In some cases it is useful to add some documenation at 2 diffent levels. Example :

```yaml
# Bla bla about persistence
persistence:
  # Enable / disable persistence
  enabled: true
```

Currently, you can't have both comments. Using the `+doc-gen:break` tag which is nice to get `persistence` comment but you won't get sub attributes description.

Do you think it might be possible to add both :

| parameter   | Description                           | Default |
| ---------------- | ------------------------------------ | --------- |
| persistence  | Bla bla about persistence    | `{ enabled: true }`  | 
| persistence.enbaled  | Enable / disable persistence   | `true`  | 

Moreover, in order to have shorter values.yaml files, it is common to add inline comments. Do you think you could handle it ?

```yaml
# Bla bla about persistence
persistence:
  enabled: true  # Enable / disable persistence
```
