### ISSUE TITLE
Support for lists

### ISSUE THREAD

**Issue by robertgates55** [kubepack/chart-doc-gen#9]
Thanks for this - really nice.

Got really excited and migrated to this format throughout, and then found that it doesn't look to handle list objects?

Some of the main values blocks in our helm chart look like

```
tenants:
  # Some desc
- name: tenant_name
  features:
    # Some other desc
    bob: foo
```

Which you often see documented like:

| Parameter               | Description     |
|-------------------------|-----------------|
| tenants[0].name         | Some desc       |
| tenants[0].features.bob | Some other desc |

Is this possible? Is this easily implemented if not?

**Comment by tamalsaha** [comment]
You are right that lists are not handled. I did not handle it because it is not clear to me how to handle that in the docs. In your example, if here are multiple array elements how does it show up in the doc?

**Comment by robertgates55** [comment]
I think just displaying the index inside square brackets seems to be closest to a standard that I’ve seen - tenants[0], tenants[1] etc - and then leaving it up to users to annotate the different elements accordingly?

**Comment by robertgates55** [comment]
Reread your question:
```
tenants:
  # Some desc
- name: tenant_name
  features:
    # A feature
  - name: bob
    # Some other desc
    bob: foo
```

Would get you:
tenants[0].features[0].name

And I think for clarity you’d maybe only ever display the 0th indexed element of any list - comments on eg the second index would be ignored?
